### ISSUE TITLE
Python Nodes are the same

### ISSUE THREAD

**Issue by matthiasmonbailleu** [herolab-uga/ROS-SEAL#1]
Hello 

I would like to use this exploration algorithm for my thesis. But I got multiple errors trying to run

"""
roslaunch seal seal_bookstore.launch
"""

After looking into it, I saw that the three python nodes are exactly the same. (seal_convex_hull.py; seal_gp.py; seal_graph.py)

Would it be possible to put them online? 

Thanks in advance!!!
Greetings

**Comment by ehsanlatif** [comment]
All script files are updated, and now the package is runnable.
