### ISSUE TITLE
About some errors when compiling and running the SEAL algorithm!

### ISSUE THREAD

**Issue by Zheng-CW** [herolab-uga/ROS-SEAL#2]
Hello, when I was compiling the SEAL algorithm, I put the turtlebot3, turtlebot3_msgs and turtle3_simulations software packages and the ROS-SEAL software package in the src directory and ran the launch file after compilation. Then the following error occurred:
![2023-10-24 18-47-36 的屏幕截图](https://github.com/herolab-uga/ROS-SEAL/assets/114415488/5bda9c71-55b4-4a2e-aa97-c685f8f61d1e)

[Err] [ REST.cc:205] Error in REST request libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'
[ WARN] [1698144499.822074024, 5.005000000]: Timed out waiting for transform from tb3_0/base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
[ WARN] [1698144499.822867029, 5.005000000]: Timed out waiting for transform from tb3_2/base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
[ WARN] [1698144499.823020787, 5.005000000]: Timed out waiting for transform from tb3_1/base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
[ WARN] [1698144504.974260776, 10.019000000]: Timed out waiting for transform from tb3_2/base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
[ WARN] [1698144504.974728892, 10.019000000]: Timed out waiting for transform from tb3_0/base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
![2023-10-24 18-49-15 的屏幕截图](https://github.com/herolab-uga/ROS-SEAL/assets/114415488/b68d84b6-a226-4a4b-a35a-6b685f58fb82)

Is it a problem with the location where I put the turtlebot3 software package? The error indicates that the coordinate system named "map" cannot be found. How to solve these problems? Thank you for giving me some advice!

**Comment by ramviyas** [comment]
It seems like an issue with your Gazebo or time sync in between your machine(s). It does not seem to be related to the ROS-SEAL package itself, as we couldn't replicate this on our end.
Try out the solutions in the Gazebo forums related to this error. https://varhowto.com/how-to-fix-libcurl-51-ssl-no-alternative-certificate-subject-name-matches-target-host-name-api-ignitionfuel-org-gazebo-ubuntu-ros-melodic/
