### ISSUE TITLE
Module Not Found Error When Building robot_msgs.msg Package

### ISSUE THREAD

**Issue by himazz** [herolab-uga/ROS-SEAL#3]
I am encountering a "Module Not Found" error when trying to build the robot_msgs.msg package in my environment. This package is intended to handle specific robotics message types (Robot_Pos, StringList), but the build process is failing, indicating that a module is missing. 

Is it a custom module ?!

**Comment by ramviyas** [comment]
It was custom module but we don't use it anymore. We just corrected the script seal_graph.py to remove this module.
Please try again after a pull.
